apiVersion: v1
kind: Service
metadata:
  labels:
    service: mediawiki
  name: mediawiki
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
  selector:
    service: mediawiki